version: "3.9"

services:
  database:
    container_name: postgres_container_openSN
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: open_sn
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

